# Generated by Django 3.1.2 on 2020-11-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('donation', '0002_auto_20201109_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='needy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.needy'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.userperson'),
        ),
    ]
